// Mocks generated by Mockito 5.4.4 from annotations
// in smart_garden/test/features/presentation/login/bloc/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i12;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_garden/base/network/errors/error.dart' as _i5;
import 'package:smart_garden/common/local_data/secure_storage.dart' as _i13;
import 'package:smart_garden/common/local_data/shared_pref.dart' as _i14;
import 'package:smart_garden/features/data/request/login_request/login_request.dart'
    as _i7;
import 'package:smart_garden/features/data/request/register_request/register_request.dart'
    as _i9;
import 'package:smart_garden/features/data/response/login_response/login_response.dart'
    as _i6;
import 'package:smart_garden/features/data/response/logout_response/logout_response.dart'
    as _i10;
import 'package:smart_garden/features/data/response/register_response/register_response.dart'
    as _i8;
import 'package:smart_garden/features/domain/entity/user_entity.dart' as _i11;
import 'package:smart_garden/features/domain/repository/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<_i2.Either<_i5.BaseError, _i6.LoginResponse>> login(
          {required _i7.LoginRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#request: request},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.BaseError, _i6.LoginResponse>>.value(
                _FakeEither_0<_i5.BaseError, _i6.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, _i6.LoginResponse>>.value(
                _FakeEither_0<_i5.BaseError, _i6.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, _i6.LoginResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.BaseError, _i8.RegisterResponse>> register(
          {required _i9.RegisterRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {#request: request},
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.BaseError, _i8.RegisterResponse>>.value(
                _FakeEither_0<_i5.BaseError, _i8.RegisterResponse>(
          this,
          Invocation.method(
            #register,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, _i8.RegisterResponse>>.value(
                _FakeEither_0<_i5.BaseError, _i8.RegisterResponse>(
          this,
          Invocation.method(
            #register,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, _i8.RegisterResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.BaseError, _i10.LogoutResponse>> logout() =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.BaseError, _i10.LogoutResponse>>.value(
                _FakeEither_0<_i5.BaseError, _i10.LogoutResponse>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, _i10.LogoutResponse>>.value(
                _FakeEither_0<_i5.BaseError, _i10.LogoutResponse>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, _i10.LogoutResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.BaseError, _i11.UserEntity>> getUserInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserInfo,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.BaseError, _i11.UserEntity>>.value(
                _FakeEither_0<_i5.BaseError, _i11.UserEntity>(
          this,
          Invocation.method(
            #getUserInfo,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, _i11.UserEntity>>.value(
                _FakeEither_0<_i5.BaseError, _i11.UserEntity>(
          this,
          Invocation.method(
            #getUserInfo,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, _i11.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.BaseError, bool>> updateUserInfo({
    String? name,
    String? currentPassword,
    String? newPassword,
    _i12.File? avatar,
    _i12.File? coverImage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [],
          {
            #name: name,
            #currentPassword: currentPassword,
            #newPassword: newPassword,
            #avatar: avatar,
            #coverImage: coverImage,
          },
        ),
        returnValue: _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
            _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #updateUserInfo,
            [],
            {
              #name: name,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
              #avatar: avatar,
              #coverImage: coverImage,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
                _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #updateUserInfo,
            [],
            {
              #name: name,
              #currentPassword: currentPassword,
              #newPassword: newPassword,
              #avatar: avatar,
              #coverImage: coverImage,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.BaseError, bool>> resendEmailVerification(
          {required String? email}) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendEmailVerification,
          [],
          {#email: email},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
            _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #resendEmailVerification,
            [],
            {#email: email},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
                _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #resendEmailVerification,
            [],
            {#email: email},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, bool>>);
}

/// A class which mocks [SecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorage extends _i1.Mock implements _i13.SecureStorage {
  @override
  _i4.Future<void> save(
    String? key,
    dynamic value, {
    bool? needEncrypt = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            key,
            value,
          ],
          {#needEncrypt: needEncrypt},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> get(
    String? key, {
    bool? needDecrypt = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#needDecrypt: needDecrypt},
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteItem(String? key) => (super.noSuchMethod(
        Invocation.method(
          #deleteItem,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i14.LocalStorage {
  @override
  _i4.Future<T?> get<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i4.Future<T?>.value(),
        returnValueForMissingStub: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<bool> validateKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #validateKey,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> save(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
