// Mocks generated by Mockito 5.4.4 from annotations
// in smart_garden/test/features/presentation/core/bloc/core_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:smart_garden/base/network/errors/error.dart' as _i5;
import 'package:smart_garden/common/local_data/shared_pref.dart' as _i13;
import 'package:smart_garden/features/data/model/chat_message_socket/chat_message_socket.dart'
    as _i12;
import 'package:smart_garden/features/data/model/web_socket_model/web_socket_model.dart'
    as _i11;
import 'package:smart_garden/features/data/request/connect_ws_request/connect_ws_request.dart'
    as _i10;
import 'package:smart_garden/features/data/request/device_token_request/device_token_request.dart'
    as _i6;
import 'package:smart_garden/features/data/request/get_chat_messages_request/get_chat_messages_request.dart'
    as _i9;
import 'package:smart_garden/features/domain/entity/chat_message_entity.dart'
    as _i8;
import 'package:smart_garden/features/domain/repository/chat_repository.dart'
    as _i7;
import 'package:smart_garden/features/domain/repository/device_token_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DeviceTokenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceTokenRepository extends _i1.Mock
    implements _i3.DeviceTokenRepository {
  @override
  _i4.Future<_i2.Either<_i5.BaseError, bool>> registerDeviceToken(
          {required _i6.DeviceTokenRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerDeviceToken,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
            _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #registerDeviceToken,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
                _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #registerDeviceToken,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.BaseError, bool>> deleteDeviceToken(
          {required _i6.DeviceTokenRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDeviceToken,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
            _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #deleteDeviceToken,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.BaseError, bool>>.value(
                _FakeEither_0<_i5.BaseError, bool>(
          this,
          Invocation.method(
            #deleteDeviceToken,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, bool>>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i7.ChatRepository {
  @override
  _i4.Future<
      _i2.Either<_i5.BaseError, List<_i8.ChatMessageEntity>>> getChatMessages(
          {required _i9.GetChatMessagesRequest? request}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChatMessages,
          [],
          {#request: request},
        ),
        returnValue: _i4.Future<
                _i2.Either<_i5.BaseError, List<_i8.ChatMessageEntity>>>.value(
            _FakeEither_0<_i5.BaseError, List<_i8.ChatMessageEntity>>(
          this,
          Invocation.method(
            #getChatMessages,
            [],
            {#request: request},
          ),
        )),
        returnValueForMissingStub: _i4.Future<
                _i2.Either<_i5.BaseError, List<_i8.ChatMessageEntity>>>.value(
            _FakeEither_0<_i5.BaseError, List<_i8.ChatMessageEntity>>(
          this,
          Invocation.method(
            #getChatMessages,
            [],
            {#request: request},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.BaseError, List<_i8.ChatMessageEntity>>>);

  @override
  _i4.Future<bool> readMessage() => (super.noSuchMethod(
        Invocation.method(
          #readMessage,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> sendMessage({required String? message}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [],
          {#message: message},
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void chatInitialize({required _i10.ConnectWSRequest? connectRequest}) =>
      super.noSuchMethod(
        Invocation.method(
          #chatInitialize,
          [],
          {#connectRequest: connectRequest},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> disconnectChat() => (super.noSuchMethod(
        Invocation.method(
          #disconnectChat,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i11.WebSocketModel<_i12.ChatMessageSocket>> wsMessageStream() =>
      (super.noSuchMethod(
        Invocation.method(
          #wsMessageStream,
          [],
        ),
        returnValue:
            _i4.Stream<_i11.WebSocketModel<_i12.ChatMessageSocket>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<_i11.WebSocketModel<_i12.ChatMessageSocket>>.empty(),
      ) as _i4.Stream<_i11.WebSocketModel<_i12.ChatMessageSocket>>);
}

/// A class which mocks [LocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorage extends _i1.Mock implements _i13.LocalStorage {
  @override
  _i4.Future<T?> get<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i4.Future<T?>.value(),
        returnValueForMissingStub: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<bool> validateKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #validateKey,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<dynamic> save(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [
            key,
            value,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
        returnValueForMissingStub: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);
}
